### ISSUE TITLE
HTTPS support not working

### ISSUE THREAD

**Issue by jochenhebbrecht** [gsoft-inc/wl-eventgrid-emulator#109]
**Describe the bug**
When configuring the Azure EventGrid emulator to also support HTTPS, the emulator crashes on startup informing the user a certificate could not be found:
```
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
```

**To Reproduce**
1. Create a Docker Compose file:
```
version: '3'

services:
  eventgridemulator:
    image: workleap/eventgridemulator:0.4.4
    ports:
      - "6500:6500"
      - "6501:6501"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6501;http://+:6500
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=##MY_PASSWORD##
    volumes:
      - "./eventgridemulator/appsettings.json:/app/appsettings.json"
      - $HOME/.aspnet/https:/https/
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
2. Start Docker Compose which results in:
```
eventgridemulator-1  | [19:49:09 ERR] Hosting failed to start
eventgridemulator-1  | System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
eventgridemulator-1  | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
eventgridemulator-1  | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
eventgridemulator-1  |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
eventgridemulator-1  | Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
eventgridemulator-1  | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
eventgridemulator-1  | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
eventgridemulator-1  |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
eventgridemulator-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
eventgridemulator-1  |    at Program.<Main>$(String[] args)
eventgridemulator-1 exited with code 139
```

**Expected behavior**
The emulator should start and serve the EventGrid topic on https://localhost:6501

**Environment (please complete the following information):**
 - OS: macOS
 - Version: 15.2 (24C101)

**Additional context**
* I have seen your documentation stating:
> As the emulator is built on top of ASP.NET Core, you can follow this [Microsoft documentation](https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https) to run on HTTPS.
* I did follow instructions as described here: https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-9.0#macos-or-linux
* I also tried this configuration:
```
version: '3'

services:
  eventgridemulator:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    ports:
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=##MY_PASSWORD##
    volumes:
      - "./eventgridemulator/appsettings.json:/app/appsettings.json"
      - $HOME/.aspnet/https:/https/
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
and this one works perfectly fine. So that proves that my ASP.NET Core environment is perfectly set up
